user root root;
worker_processes auto;
worker_cpu_affinity auto;
worker_rlimit_nofile 51200;

events {
    worker_connections 1024;
}

http {
    proxy_cache_path /tmp levels=1:2 keys_zone=my_cache:10m max_size=100m inactive=60m use_temp_path=off;

    sendfile on;
    keepalive_timeout 3600;

    server {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        listen ${NGINX_PORT};
        listen [::]:${NGINX_PORT};
        server_name publish_helper;

        # 全局启用基础认证
        auth_basic "Restricted System";
        auth_basic_user_file /etc/nginx/.htpasswd;

        # 主目录（现在需要认证）
        location / {
            expires off;
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            root /public;
            try_files $uri $uri/ /index.html;
        }

        # API接口
        location /api {
            proxy_pass http://backend_api;
            rewrite ^.+mock-server/?(.*)$ /$1 break;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_cache off;
            proxy_redirect off;
            proxy_set_header Connection "";
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-Nginx-Proxy true;
            proxy_read_timeout 600s;
        }

        # 可选：排除特定文件类型的认证（如需）
        location ~* \.(jpg|css|js|png)$ {
            auth_basic off;
            expires 7d;
            add_header Cache-Control "public";
        }
    }

    upstream backend_api {
        server 127.0.0.1:${API_PORT};
    }
}
